deploy: ef3b7e40ab064ab40ef5ac677a1fb8a69bd56937

diff --git a/doc/test b/doc/test
--- a/doc/test
+++ b/doc/test
@@ -1,2 +1,11 @@
-#!/usr/bin/env bash
-awk 'BEGIN { lean = 0 } /```/ { if (lean == 1) lean = 0; } { if (lean == 1) { sub(/# /, ""); print $0 } } /```lean/ && !/```lean,ignore/ { lean = 1 }' $1 | lean --stdin
+#!/nix/store/2jysm3dfsgby5sw5jgj43qjrb5v79ms9-bash-4.4-p23/bin/bash
+awk 'BEGIN { lean = 0; idx = 0 } /```/ { if (lean == 1) lean = 0; } { if (lean == 1) { sub(/# /, ""); print $0 > out } } /```lean/ && !/```lean,ignore/ { lean = 1; idx = idx + 1; out = FILENAME "." idx ".lean" }' $1
+for f in `ls $1.*.lean`; do
+  echo "testing $f"
+  if ! lean $f; then
+      echo "FAILED"
+      rm -f $1.*.lean
+      exit 1
+  fi
+  rm $f
+done
